
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: facebookclone_development
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  database: facebookclone_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: facebookclone_production
  pool: 5
  timeout: 5000
